version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: weblab4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  server:
    build: 
      context: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
  
  client:
    build:
      context: ./client
    ports:
      - "9000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: